# Automated Actions Configuration

# Resource limits
resource_limits:
  cpu_limit: 90  # percentage
  memory_limit: 90  # percentage
  disk_limit: 90  # percentage
  network_limit: 1000  # MB/s

# Auto-scaling configuration
scaling:
  enabled: true
  min_replicas: 1
  max_replicas: 10
  cpu_threshold: 80
  memory_threshold: 80
  cool_down_period: 300  # seconds
  scaling_policies:
    - metric: cpu_usage
      threshold: 80
      action: scale_up
      factor: 2
    - metric: memory_usage
      threshold: 80
      action: scale_up
      factor: 2
    - metric: cpu_usage
      threshold: 20
      action: scale_down
      factor: 0.5

# Recovery configuration
recovery:
  max_attempts: 3
  backoff_time: 30  # seconds
  strategies:
    - type: restart
      max_attempts: 3
      backoff_time: 30
    - type: redeploy
      max_attempts: 2
      backoff_time: 60
    - type: rollback
      max_attempts: 1
      backoff_time: 0

# Maintenance configuration
maintenance:
  disk_cleanup:
    enabled: true
    threshold: 90  # percentage
    min_free_space: 10  # GB
    retention_periods:
      logs: 30  # days
      temp_files: 7  # days
      backups: 90  # days
  
  docker_cleanup:
    enabled: true
    prune_interval: 86400  # seconds (1 day)
    image_retention: 30  # days
    volume_retention: 7  # days
  
  system_cleanup:
    enabled: true
    cache_cleanup: true
    temp_cleanup: true
    package_cleanup: true

# Container configuration
containers:
  health_check:
    interval: 60  # seconds
    timeout: 10  # seconds
    retries: 3
  
  resource_limits:
    cpu: 2  # cores
    memory: 2048  # MB
    storage: 10  # GB
  
  restart_policy:
    condition: any
    delay: 5  # seconds
    max_attempts: 3
    window: 120  # seconds

# Kubernetes configuration
kubernetes:
  namespaces:
    - default
    - kube-system
  
  health_check:
    enabled: true
    interval: 60  # seconds
  
  auto_scaling:
    enabled: true
    metrics:
      - type: Resource
        resource:
          name: cpu
          target_average_utilization: 80
      - type: Resource
        resource:
          name: memory
          target_average_utilization: 80
  
  resource_quotas:
    enabled: true
    default_limits:
      cpu: 4
      memory: 8Gi
      storage: 20Gi

# System resource management
system:
  process_priorities:
    enabled: true
    high_cpu_threshold: 50  # percentage
    nice_value: 10
  
  io_scheduling:
    enabled: true
    class: best-effort
    priority: 7
  
  memory_management:
    enabled: true
    swappiness: 60
    cache_pressure: 100
    min_free_kbytes: 65536

# Monitoring configuration
monitoring:
  metrics_collection:
    interval: 60  # seconds
    retention: 30  # days
  
  alert_thresholds:
    cpu_usage: 90
    memory_usage: 90
    disk_usage: 90
    network_usage: 1000
  
  log_collection:
    enabled: true
    log_level: INFO
    max_size: 100  # MB
    backup_count: 5

# Security configuration
security:
  auto_updates:
    enabled: true
    schedule: "0 4 * * *"  # 4 AM daily
  
  vulnerability_scanning:
    enabled: true
    schedule: "0 2 * * *"  # 2 AM daily
    fail_on_critical: true
  
  compliance:
    enabled: true
    standards:
      - CIS
      - NIST
    auto_remediate: true

# Backup configuration
backup:
  enabled: true
  schedule: "0 1 * * *"  # 1 AM daily
  retention: 30  # days
  types:
    - configuration
    - data
    - logs
  compression: true
  encryption: true

# Notification configuration
notifications:
  enabled: true
  channels:
    - type: slack
      webhook_url: "{{SLACK_WEBHOOK_URL}}"
      events:
        - scaling
        - recovery
        - maintenance
    - type: email
      address: "blaine.winslow@gmail.com"
      events:
        - error
        - critical

